### ISSUE TITLE
Verify checksum of the Hugo binary in Travis CI

### ISSUE THREAD

**Issue by pawlobanano** [pawlobanano/personal-website#9]
### Problem
Sha256 checksum of the Hugo binary is currently not verified during the CI process.

### Solution
Verify Go binary in the CI process.

### Explanation
The plan is to get Hugo binary, plus text file with sha256 checksums of the current version Hugo binaries. 
Then getting sha256 checksum of downloaded Hugo binary file.
Then check if downloaded checksum text file holds the checksum of downloaded Hugo binary file inside.
If true then go ahead, if false then stop the CI process.

**Comment by pawlobanano** [comment]
I'm working on it

**Comment by pawlobanano** [comment]
I came up with such a `grep` solution: 
`grep $(sha256sum $hugoGzip | awk '{print $1}') $checksumFile`

Already tested locally (not in the CI process). 
I will prepare PR.

**Comment by pawlobanano** [comment]
I came up with such a solution:
```yml
---
language: go
go: stable

git:
  depth: false

branches:
  only: STAGING

install:
- curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep browser_download_url | grep hugo | grep -v hugo_extended | grep Linux-64bit.tar.gz | cut -d '"' -f 4 | wget -qi -
- curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep browser_download_url | grep hugo | grep _checksums.txt | cut -d '"' -f 4 | wget -qi -
- hugoGzip=$(ls -t *Linux-64bit.tar.gz | head -1)
- checksumFile=$(ls -t *_checksums.txt | head -1)
- grep $(sha256sum $hugoGzip | awk '{print $1}') $checksumFile
- sudo tar -zxf $hugoGzip -C /usr/local/bin hugo
- npm install -g firebase-tools

script: rm -rf public/* && hugo && firebase deploy -P STAGING --token $FIREBASE_TOKEN

env:
  global:
  - secure: j4CfBlB+T0VwOiBMyPF+It09FV/4uLwuxQFWsrwAoF/qQo5VsjidYiOTdG7iEiIJMWUZhBZ4nhb9P9yfp1rNi4k9RFWsHKHCmxfDqnTOD07mZOB5tegUsykDmUxoJragRMQ6rRRu5Uy1foTkxi9DkXbNEW1B6v7UCh44CMnViTKwncx5mOT7shIHBzbENcj2KDcZf1W3IlLBtDr4mOoN25X5hKBudMF8iFCI/BfZbWePalh5J2cCsup2Y+tNO6vLU0XmEY84XCLUuPAVvTmqIq9z6BHvo+ahcfGIz4F7bqB2QOhJytYYsigHSz3mH1VMyd0DmoqI+2z280Qsc3nHd81GJaeeJf1ze91Pd38roPnDbtWfxrLB7dSKb+MWsnktZbp3BzX7UJWE97IF6Iu1STxzmMUk1e1L36cPWvO3nJG8vOByeN2YMYRguRypuPz6B26/fi4Aq9Ip0v7Bvry1oESzewEYLG8tzFOVeaAfSby3F5fjy/WGSsUpvrwMYUAfvmp7H0UsneUnct/ZCq9uhKReGXBWO1qKJh3ZXcAIzkuekknGQ4VPWhgnf7Us/EYlun6vaAGvYXW+hCIPsyLEWcGo4e7iZndniemWlp4hR28MTpS79WT92V+xe1ATg4+kphl8wo/doW2Wg2LOuxxjupgvl94Jz53SDosfRe+bsWs=
```

It should work. I tested it locally in CLI. But I can't test it with Travis CI due to #11.
**I suggest we considered this issue done.** And I will create another one, but for GitHub Action after #12 is done.
